### ISSUE TITLE
error - TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by ashwat07** [brianlovin/briOS#1766]
TypeError: Cannot read property 'trim' of undefined
    at ServerClient.BaseClient (I:\react\briOS\node_modules\postmark\dist\client\BaseClient.js:22:28)
    at new ServerClient (I:\react\briOS\node_modules\postmark\dist\client\ServerClient.js:28:23)
    at eval (webpack-internal:///./src/lib/postmark/index.ts:13:16)
    at Object../src/lib/postmark/index.ts (I:\react\briOS\.next\server\pages\404.js:770:1)
    at __webpack_require__ (I:\react\briOS\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/graphql/resolvers/mutations/comment/index.tsx:11:71)
    at Object../src/graphql/resolvers/mutations/comment/index.tsx (I:\react\briOS\.next\server\pages\404.js:473:1)
    at __webpack_require__ (I:\react\briOS\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/graphql/resolvers/mutations/index.ts:8:94)
    at Object../src/graphql/resolvers/mutations/index.ts (I:\react\briOS\.next\server\pages\404.js:495:1)

**Comment by zonito** [comment]
Same here!

**Comment by ashwat07** [comment]
Yes

**Comment by brianlovin** [comment]
Gotcha, thanks for the heads up — this is likely because you don't have any environment variables defined. You'll need either a `.env` file, or if you use Vercel you can use `vercel dev` and host your secrets directly on your Vercel project (this is what I do).
