### ISSUE TITLE
Error: Expected undefined to be a GraphQL schema.

### ISSUE THREAD

**Issue by zonito** [brianlovin/briOS#1767]
```
error - Error: Expected undefined to be a GraphQL schema.
{
  err: Error: Expected undefined to be a GraphQL schema.
      at assertSchema (/briOS/node_modules/graphql/type/schema.js:47:11)
      at validateSchema (briOS/node_modules/graphql/type/validate.js:42:28)
      at assertValidSchema (briOS/node_modules/graphql/type/validate.js:66:16)
      at assertValidExecutionArguments (briOS/node_modules/graphql/execution/execute.js:150:35)
      at executeImpl (briOS/node_modules/graphql/execution/execute.js:98:3)
      at Object.execute (briOS/node_modules/graphql/execution/execute.js:60:63)
      at /node_modules/@apollo/link-schema/lib/index.js:19:39
      at new Subscription (briOS/node_modules/zen-observable/lib/Observable.js:197:34)
      at Observable.subscribe (node_modules/zen-observable/lib/Observable.js:279:14)
      at briOS/node_modules/@apollo/client/link/error/error.cjs.js:16:42
}
```

PS: Please provide `README.md` and `.env.local.template`

**Comment by brianlovin** [comment]
Are you running this locally?

**Comment by zonito** [comment]
yes

**Comment by brianlovin** [comment]
Gotcha, I'm not quite sure what's going wrong here, but I'm not going to be able to offer much support for folks cloning this.
